api:
  prefix: /api/**
apiUrl: https://www.google.com/recaptcha/api/siteverify
reCaptcha:
  secretKey: 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
header:
  cors:
    methods:
      allow: GET, PUT, POST
    origins:
      allow: 'http://10.0.0.1:8080 , http://10.10.8.2:8080 , http://10.12.8.12:7401 '
server:
  port: 8099
spring:
  data:
    mongodb:
      database: mongo-spring
      host: 192.168.99.109
      password: root
      port: 27017
      username: root
